databases:  
  - name: employee_recognition
    databaseName: employee_recognition
    user: employee_recognition
    plan: free
    ipAllowList: []

services:
  - type: web
    name: employee_recognition
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: employee_recognition
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction